# Generated by Django 3.2.7 on 2021-09-22 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
                ('home_link_more', models.CharField(max_length=100)),
                ('home_logo', models.ImageField(upload_to='company/logos')),
                ('image_block_1', models.ImageField(upload_to='company/blocks')),
                ('description_title', models.TextField(blank=True, help_text='descripcion con tamaño mayor para Opciones', null=True)),
                ('description', models.TextField(help_text='descripcion para home y primer bloque menor tamaño')),
                ('middle_message', models.TextField(blank=True, help_text='mensaje entre bloque y bloque', null=True)),
                ('image_block_2', models.ImageField(blank=True, null=True, upload_to='company/blocks')),
                ('description_block_2', models.TextField(blank=True, help_text='descripcion para el bloque 2', null=True)),
                ('description_title_block_2', models.TextField(blank=True, help_text='descripcion con tamaño mayor para Opciones', null=True)),
                ('title_block_3', models.CharField(blank=True, max_length=100, null=True)),
                ('image_block_3', models.ImageField(blank=True, null=True, upload_to='company/blocks')),
                ('background_block_3', models.ImageField(blank=True, null=True, upload_to='company/blocks')),
                ('logo_company_block_3', models.ImageField(blank=True, null=True, upload_to='company/blocks')),
                ('description_title_block_3', models.TextField(blank=True, null=True)),
                ('description_block_3', models.TextField(blank=True, null=True)),
                ('icon_1_block_4', models.ImageField(blank=True, null=True, upload_to='company/blocks')),
                ('title_1_block_4', models.CharField(blank=True, max_length=100, null=True)),
                ('description_1_block_4', models.TextField(blank=True, null=True)),
                ('icon_2_block_4', models.ImageField(blank=True, null=True, upload_to='company/blocks')),
                ('title_2_block_4', models.CharField(blank=True, max_length=100, null=True)),
                ('description_2_block_4', models.TextField(blank=True, null=True)),
                ('icon_3_block_4', models.ImageField(blank=True, null=True, upload_to='company/blocks')),
                ('title_3_block_4', models.CharField(blank=True, max_length=100, null=True)),
                ('description_3_block_4', models.TextField(blank=True, null=True)),
                ('company_web_page_link', models.CharField(blank=True, max_length=250, null=True)),
                ('company_web_page_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='company/sliders')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
