# Generated by Django 3.2.7 on 2021-09-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='block_1_video',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
