# Generated by Django 3.2.7 on 2021-09-28 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_company_image_block_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
